### ISSUE TITLE
feature request: open research results in new tab

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/fancy_research_links#10]
I think it would be a great idea to make an option to open the research results in a new browser tab (with "target=_blank"). At the moment they are opened in the same tab as webtrees, so I have always use the navigation of my browser to come back.
Of course some people like this way, but I like to work with parallel opened tabs, so I can make more than one task at one time.
I don't ask to change this in general - just as a setting!

**Comment by JustCarmen** [comment]
This was the default behavior until one or two releases ago. I removed it since it is against webtrees own policy. Force links to open in a new tab is user unfriendly on touch screen devices.

But you have several options to open the links in a new tab:
* ctrl. click a link
* context menu: open link in new tab
* use a browser extension: [Open External links in New Tab (Chrome)](Open External Links in New Tab). In Firefox I use [Tabmix Plus](http://tabmixplus.org/) where you can set the option to open external links in a new tab.
